- hosts: all
  roles:
    - role: basic

- hosts: dbs
  roles: 
    - role: db

- hosts: webs
  roles:
    - role: web

- hosts: nfs
  roles:
    - role: nfs
      nfs_exports:
        - path: "/data/wp"
          ip: "172.16.1.0/24"

- hosts: dbs
  roles:
    - role: db_item  
      item_db_name: "wordpress"
      db_root_password: "mariohy"
      db_server_ip: "localhost"

- hosts: webs
  vars:
    # nfs
    nfs_export_path: "/data/wp"
    nfs_server_ip: "172.16.1.31"
    # nginx conf
    wp_code_dir: "/code/wordpress"
    wp_domain: "wp.test.com"
    # wp-config.php
    wp_db_name: "wordpress"
    wp_db_user: "mariohy"
    wp_db_pass: "mariohy"
    db_server_ip: "172.16.1.51"
 
  roles:
    - role: wordpress
  tasks:
    - name: Install nfs-utils
      yum:
        name: nfs-utils
        state: present

    - name: Mount WordPress uploads from NFS
      mount:
        path: "{{ wp_code_dir }}/wp-content/uploads"
        src: "{{ nfs_server_ip }}:{{ nfs_export_path }}"
        fstype: nfs
        opts: defaults
        state: mounted


- hosts: nfs
  roles:
    - role: nfs
      nfs_exports:
        - path: "/data/she"
          ip: "172.16.1.0/24"

- hosts: dbs
  roles:
    - role: db_item
      item_db_name: "phpshe"
      db_root_password: "mariohy"
      db_server_ip: "localhost"

- hosts: webs
  vars:
    # nginx conf
    she_code_dir: "/code/she"
    she_domain: "she.test.com"
    # config.php
    db_server_ip: "172.16.1.51"
    she_db_name: "phpshe"
    she_db_user: "mariohy"
    she_db_pass: "mariohy"
    # nfs
    nfs_server_ip: "172.16.1.31"
    nfs_export_path: "/data/she"
    # db root pass
    db_root_pass: "mariohy"
    role_path: "roles/phpshe"
    
  pre_tasks:
    - name: Install nfs-utils and mariadb
      yum:
        name: 
          - nfs-utils
          - mariadb
        state: present
  roles:
    - phpshe
  tasks:
    - name: Deploy data package to NFS server
      unarchive:
        src: "{{ role_path }}/files/data.tar.gz"
        dest: "{{ nfs_export_path }}/"
        owner: www        
        group: www
        extra_opts: ['--strip-components=1']
      delegate_to: "{{ nfs_server_ip }}"
      run_once: true

    - name: Mount PHPSHE data from NFS
      mount:
        path: "{{ she_code_dir }}/data"
        src: "{{ nfs_server_ip }}:{{ nfs_export_path }}"
        fstype: nfs
        opts: defaults
        state: mounted

- hosts: webs
  roles:
    - role: phpMyAdmin
      vars:
        pma_code_dir: "/code/admin"
        pma_domain: "admin.test.com"

- hosts: redis
  roles:
    - role: redis
      vars:
        redis_bind: 172.16.1.21

- hosts: webs
  roles:
    - role: redis_phpconf
      vars:
        # Redis connection info     
        redis_server_ip: "172.16.1.21"
        redis_server_port: 6379     
        # if redis has a password
        # redis_server_auth: "123"  
        php_ini_path: "/etc/php.ini"
        php_fpm_www_conf: "/etc/php-fpm.d/www.conf"

