# Redis connection info
redis_server_ip: "172.16.1.21"
redis_server_port: 6379

# Uncomment and set if redis has a password
# redis_server_auth: "123"

# Config file paths
php_ini_path: "/etc/php.ini"
php_fpm_www_conf: "/etc/php-fpm.d/www.conf"

