server {
    listen 80;
    server_name test.test.com;
    root /code;
    charset utf-8,gbk;

    location / {
        index index.html;
        set $ip 0;       # 设置变量为0
        if ($remote_addr = "192.168.192.1"){
            set $ip 1;   # 如果来源IP为0.1则设置为1
        }
        if ($ip = 0){    # 判断如果变量为0 则跳转维护页面
            rewrite ^(.*)$ /wh.html break;
        }
    }

}
