server {
        listen 80;
        server_name wp.test.com;
        root /code/wordpress;

        location / {
                index index.php index.html;
        }

        location ~ \.php$ {
                include fastcgi_params;
                fastcgi_index index.php;
                fastcgi_pass 127.0.0.1:9000;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		#告诉PHP我前置的负载使用的是https协议
		fastcgi_param HTTPS on;
        }
}
