php_pack:
  - /opt/autoconf-2.69-11.el7.noarch.rpm
  - /opt/automake-1.13.4-3.el7.noarch.rpm
  - /opt/libevent-2.0.21-4.el7.x86_64.rpm
  - /opt/libjpeg-turbo-1.2.90-8.el7.x86_64.rpm
  - /opt/libmcrypt-2.5.8-13.el7.x86_64.rpm
  - /opt/libmemcached-1.0.16-5.el7.x86_64.rpm
  - /opt/libtool-ltdl-2.4.2-22.el7_3.x86_64.rpm
  - /opt/libX11-1.6.7-3.el7_9.x86_64.rpm
  - /opt/libX11-common-1.6.7-3.el7_9.noarch.rpm
  - /opt/libXau-1.0.8-2.1.el7.x86_64.rpm
  - /opt/libxcb-1.13-1.el7.x86_64.rpm
  - /opt/libXpm-3.5.12-1.el7.x86_64.rpm
  - /opt/libxslt-1.1.28-6.el7.x86_64.rpm
  - /opt/mod_php71w-7.1.33-1.w7.x86_64.rpm
  - /opt/pcre-devel-8.32-17.el7.x86_64.rpm
  - /opt/perl-Data-Dumper-2.145-3.el7.x86_64.rpm
  - /opt/perl-Test-Harness-3.28-3.el7.noarch.rpm
  - /opt/perl-Thread-Queue-3.02-2.el7.noarch.rpm
  - /opt/php71w-cli-7.1.33-1.w7.x86_64.rpm
  - /opt/php71w-common-7.1.33-1.w7.x86_64.rpm
  - /opt/php71w-devel-7.1.33-1.w7.x86_64.rpm
  - /opt/php71w-embedded-7.1.33-1.w7.x86_64.rpm
  - /opt/php71w-fpm-7.1.33-1.w7.x86_64.rpm
  - /opt/php71w-gd-7.1.33-1.w7.x86_64.rpm
  - /opt/php71w-mbstring-7.1.33-1.w7.x86_64.rpm
  - /opt/php71w-mcrypt-7.1.33-1.w7.x86_64.rpm
  - /opt/php71w-mysqlnd-7.1.33-1.w7.x86_64.rpm
  - /opt/php71w-opcache-7.1.33-1.w7.x86_64.rpm
  - /opt/php71w-pdo-7.1.33-1.w7.x86_64.rpm
  - /opt/php71w-pear-1.10.4-1.w7.noarch.rpm
  - /opt/php71w-pecl-igbinary-2.0.5-1.w7.x86_64.rpm
  - /opt/php71w-pecl-memcached-3.0.4-1.w7.x86_64.rpm
  - /opt/php71w-pecl-mongodb-1.5.3-1.w7.x86_64.rpm
  - /opt/php71w-pecl-redis-3.1.6-1.w7.x86_64.rpm
  - /opt/php71w-process-7.1.33-1.w7.x86_64.rpm
  - /opt/php71w-xml-7.1.33-1.w7.x86_64.rpm

